<!-- jQuery依赖 -->
<script type="text/javascript" src="/assets/js/jquery.js"></script>
<!-- 日期处理依赖 -->
<script type="text/javascript" src="/assets/js/moment.js"></script>
<!-- Bootstrap依赖 -->
<script type="text/javascript" src="/assets/js/bootstrap.js"></script>
<!-- Vue核心依赖 -->
<script type="text/javascript" src="/assets/js/vue.js"></script>
<!-- Vue生态resource/validation/router/vuex等依赖 -->
<script type="text/javascript" src="/assets/js/vue-platform.js"></script>
<!-- 其他通用插件依赖 -->
<script type="text/javascript" src="/assets/js/plugins.js"></script>
<!-- 项目需要依赖 -->
<script type="text/javascript" src="/assets/js/vendor.js"></script>